# Generated by Django 5.2.8 on 2025-11-25 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASIGNACION_DOCENTE', 'Asignación de Docente Asesor'), ('CAMBIO_ESTADO_PRACTICA', 'Cambio de Estado de Práctica'), ('POSTULACION_ACEPTADA', 'Postulación Aceptada'), ('POSTULACION_RECHAZADA', 'Postulación Rechazada'), ('HOJA_VIDA_APROBADA', 'Hoja de Vida Aprobada'), ('HOJA_VIDA_RECHAZADA', 'Hoja de Vida Rechazada'), ('ENCUENTRO_PROGRAMADO', 'Encuentro Programado'), ('RECORDATORIO_ENCUENTRO', 'Recordatorio de Encuentro'), ('RESULTADO_EVALUACION', 'Resultado de Evaluación'), ('OTROS', 'Otros')], default='OTROS', max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('postulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.postulacion')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
