# Generated by Django 5.2.8 on 2025-11-25 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='practica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practicas.practica'),
        ),
    ]
