# Generated by Django 5.2.8 on 2025-11-25 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuentroSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('tema', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('acuerdos', models.TextField(blank=True, null=True)),
                ('asistencia_estudiante', models.BooleanField(default=True)),
                ('asistencia_docente', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluador', models.CharField(choices=[('DOCENTE', 'Docente Asesor'), ('INSTRUCTOR', 'Instructor')], max_length=20)),
                ('evaluador_id', models.IntegerField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rubro', models.CharField(default='Desempeño General', max_length=255)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('NO_INICIADA', 'No Iniciada'), ('EN_CURSO', 'En Curso'), ('EN_PAUSA', 'En Pausa'), ('FINALIZADA', 'Finalizada'), ('REPROBADA', 'Reprobada')], default='NO_INICIADA', max_length=20)),
                ('promedio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('puede_pasar_a_siguiente', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['estudiante', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('objetivos', models.TextField()),
                ('actividades', models.TextField()),
                ('registro_archivo', models.FileField(blank=True, null=True, upload_to='proyectos/')),
                ('informe_final_archivo', models.FileField(blank=True, null=True, upload_to='informes/')),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('cronograma', models.TextField(blank=True, null=True)),
                ('competencias_desarrolladas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
