# Generated by Django 5.2.8 on 2025-11-25 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('practicas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentrosemanal',
            name='registrado_por_docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.docenteasesor'),
        ),
        migrations.AddField(
            model_name='practica',
            name='docente_asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_asesoradas', to='usuarios.docenteasesor'),
        ),
        migrations.AddField(
            model_name='practica',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='practica',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_tutoriadas', to='usuarios.instructor'),
        ),
        migrations.AddField(
            model_name='practica',
            name='vacante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.vacante'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='practicas.practica'),
        ),
        migrations.AddField(
            model_name='encuentrosemanal',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='practicas.practica'),
        ),
        migrations.AddField(
            model_name='proyectopractica',
            name='practica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='practicas.practica'),
        ),
        migrations.AlterUniqueTogether(
            name='practica',
            unique_together={('estudiante', 'numero')},
        ),
    ]
