# Generated by Django 5.2.8 on 2025-11-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('ESTUDIANTE', 'Postulación del Estudiante'), ('COORDINADOR', 'Asignación del Coordinador')], default='ESTUDIANTE', max_length=20)),
                ('estado', models.CharField(choices=[('EN_REVISION', 'En Revisión'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='EN_REVISION', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('perfil_requerido', models.TextField()),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido'), ('REMOTO', 'Remoto')], default='PRESENCIAL', max_length=20)),
                ('duracion_meses', models.IntegerField(default=6)),
                ('salario_rango', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_plazas', models.IntegerField(default=1)),
                ('fecha_inicio_estimada', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
