# Generated by Django 5.2.8 on 2025-11-25 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='empresas.vacante'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('estudiante', 'vacante')},
        ),
    ]
