# Generated by Django 5.2.8 on 2025-11-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('dirigida_a_roles', models.CharField(help_text='Roles destinatarios separados por comas', max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('ESCALA', 'Escala (1-5)'), ('OPCION_MULTIPLE', 'Opción Múltiple'), ('TEXTO', 'Texto Abierto'), ('SI_NO', 'Sí/No')], default='ESCALA', max_length=20)),
                ('requerida', models.BooleanField(default=True)),
                ('opciones', models.TextField(blank=True, help_text='Para opción múltiple, separar con | (ej: Opción1|Opción2|Opción3)', null=True)),
            ],
            options={
                'ordering': ['encuesta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('respuesta_valor', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_respuesta'],
            },
        ),
    ]
